### ISSUE TITLE
No such service build

### ISSUE THREAD

**Issue by ChBasitGill** [aspnetrun/run-aspnetcore-microservices#1]
WARNING: The WEBAPP_STORAGE_HOME variable is not set. Defaulting to a blank string.
WARNING: The HOME variable is not set. Defaulting to a blank string.
ERROR: No such service: build

**Comment by mehmetozkaya** [comment]
Can you please use below command when compose docker file ? In some cases "-build" parameter gives that error so I replace it "-d" parameter in order run background.

docker-compose -f docker-compose.yml -f docker-compose.override.yml up –d

**Comment by ChBasitGill** [comment]
Thanks, it is working fine now.
