### ISSUE TITLE
docker-compose command is not working

### ISSUE THREAD

**Issue by kias2014** [aspnetrun/run-aspnetcore-microservices#14]
Hi 

after executing 
"docker-compose -f docker-compose.yml -f docker-compose.override.yml up –d" 
below error will get

![Capture](https://user-images.githubusercontent.com/11784726/114295820-37c7ae00-9ac5-11eb-9f40-5dfedf4b7389.PNG)

**Comment by mehmetozkaya** [comment]
I don't know why but somehow the dash (-) character comes long when you copy paste to your window.
Please remove -d and write again -d with correcting dash character.
