### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error	DT1001	ERROR: for catalog.api  Cannot create container for service catalog.api: Duplicate mount point: /root/.aspnet/https If the error persists, try restarting Docker Desktop.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	384	

### ISSUE THREAD

**Issue by punkouter2018** [aspnetrun/run-aspnetcore-microservices#2]
Got this error while building container. any idea ?

**Comment by mehmetozkaya** [comment]
it seems error occurs from the volume definitions. Once you defined before some other projects it gives a duplicate mount error.
Could you please remove all aspnet generated volumes (as below lines) from docker-compose.override.yml file and try again ?

volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/

**Comment by punkouter2018** [comment]
catalog api get has this error
RabbitMQ.Client.Exceptions.BrokerUnreachableException: 'None of the specified endpoints were reachable'

Is it suppose to be as simple as docker compose up and everything just works ?  Im new to this.

**Comment by mehmetozkaya** [comment]
yes exactly, if you run docker desktop on your local, all you need to run below command on top of the docker-compose file.
docker-compose -f docker-compose.yml -f docker-compose.override.yml up –d

Catalog has no any dependency of RabbitMQ so error should come from different container.

Could you please send me the image and what steps you are following before that ?

**Comment by punkouter2018** [comment]
I was trying to F5 the dock compose in VS2019.. Ill try the command line..
