### ISSUE TITLE
ERROR: for shopping.aggregator  Cannot start service shopping.aggregator: Ports are not available: listen tcp 0.0.0.0:8005: 

### ISSUE THREAD

**Issue by gawandashish** [aspnetrun/run-aspnetcore-microservices#24]
After running "docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d", I am getting following error ->
discount.api is up-to-date
basket.api is up-to-date
ocelotapigw is up-to-date
Starting shopping.aggregator ...
Starting shopping.aggregator ... error

ERROR: for shopping.aggregator  Cannot start service shopping.aggregator: Ports are not available: listen tcp 0.0.0.0:8005: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

ERROR: for shopping.aggregator  Cannot start service shopping.aggregator: Ports are not available: listen tcp 0.0.0.0:8005: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
ERROR: Encountered errors while bringing up the project.

Could you please help me on this?

**Comment by mehmetozkaya** [comment]
Your 8005 port is using from other threads, so you need to change this port number something else in docker-compsose override file.
