### ISSUE TITLE
Possible invalid lifetime for EmailService

### ISSUE THREAD

**Issue by pharazfadaei** [aspnetrun/run-aspnetcore-microservices#26]
According to the course lectures, the reasoning behind registering the email service as transient is to prevent the service from being created for every request and to use a single instance throughout the application lifetime. This means that the service must be registered as singleton since transient means a new instance will be created EVERY TIME the service is requested from the dependency injection framework. 
[Code](https://github.com/aspnetrun/run-aspnetcore-microservices/blob/beb26214e4d464e09ccbb11a7bdc9316eaf7b50b/src/Services/Ordering/Ordering.Infrastructure/InfrastructureServiceRegistration.cs#L24)

**Comment by mehmetozkaya** [comment]
so what is your recommendation ? should I use singleton on there ?

**Comment by pharazfadaei** [comment]
Yes. If you intend to have a single instance of EmailService for all requests, singleton is the appropriate lifetime.

**Comment by mehmetozkaya** [comment]
thanks for sharing this. I will consider and refactor this part. thanks.
